export class DeclaredSonarServer {

	/**
	 * Declared Sonars declared in the referential of the Fitzhi backend.
	 * 2 credentials are available :
	 *
	 * - either the pair user/password,
	 * - or the login token.
	 *
	 * @param urlSonarServer the madatory Sonar URL
	 * @param user the facultative user
	 * @param password the facultative password associated with the user
	 * @param login the login token generated by Sonar
	 */
	constructor(
		public urlSonarServer: string,
		public user?: string,
		public password?: string,
		public login?: string) {
	}
}
