/**
 * 
 */
package com.fitzhi.bean;

import java.util.List;
import java.util.Map;

import com.fitzhi.data.internal.Project;
import com.fitzhi.data.internal.ProjectLayer;
import com.fitzhi.data.internal.Skill;
import com.fitzhi.data.internal.SourceControlChanges;
import com.fitzhi.data.internal.Staff;
import com.fitzhi.exception.SkillerException;

/**
 * Interface in charge of saving & loading data.
 * @author Fr&eacute;d&eacute;ric VIDAL
 */
public interface DataHandler {

	/**
	 * Save projects on a persistent media
	 * @param projects list of projects
	 * @throws SkillerException thrown if exception occurs during the saving process
	 */
	void saveProjects(Map<Integer, Project> projects) throws SkillerException;
	
	
	/**
	 * Load the projects from a persistent media
	 * @return the map of projects
	 * @throws SkillerException thrown if exception occurs during the saving process
	 */
	Map<Integer, Project> loadProjects() throws SkillerException;

	/**
	 * Save the staff on a persistent media
	 * @param staff list of staff
	 * @throws SkillerException thrown if exception occurs during the saving process
	 */
	void saveStaff(Map<Integer, Staff> staff) throws SkillerException;
	
	
	/**
	 * Load the staff members from a persistent media
	 * @return the staff
	 * @throws SkillerException thrown if exception occurs during the saving process
	 */
	Map<Integer, Staff> loadStaff() throws SkillerException;

	/**
	 * Save the skills <i>(probably for this first release)</i> on the file system
	 * @param staff list of staff
	 * @throws SkillerException thrown if an exception occurs during the saving process
	 */
	void saveSkills(Map<Integer, Skill> staff) throws SkillerException;
	
	/**
	 * <p>
	 * generate the build layers of the given project.
	 * </br>
	 * Each layer represents the size of the project, day by day.
	 * </p>
	 * @param project project whose changes have to be serialized in CSV
	 * @param changes changes retrieved from the repository
	 * @throws SkillerException thrown if an exception occurs during the saving process
	 */
	List<ProjectLayer> generateProjectLayers(Project project, SourceControlChanges changes) throws SkillerException;

	/**
	 * <p>
	 * Save the build layers generated by {@link #generateProjectLayers(Project, SourceControlChanges)}
	 * </p>
	 * This file is formated in CSV format into order to optimize the bandwidth. 
	 * @param layers list of project layers
	 * @throws SkillerException thrown if an exception occurs during the saving process
	 */
	 void saveProjectLayers(List<ProjectLayer> layers) throws SkillerException;

	/**
	 * <p>
	 * Save the source control changes loaded from the repository for cache & debug purpose.
	 * </p>
	 * <p><i>Due to the DEBUG purpose of this file, the output format will <b>CSV</b></i>.</p>
	 * @param project project whose changes have to be serialized in CSV
	 * @param changes changes retrieved from the repository
	 * @throws SkillerException thrown if an exception occurs during the saving process
	 */
	void saveChanges(Project project, SourceControlChanges changes) throws SkillerException;

	/**
	 * Load the skills <i>(probably for this first release)</i> from the file system
	 * @return the skills collection, retrieved from the file system
	 * @throws SkillerException thrown if an exception occurs during the saving process
	 */
	Map<Integer, Skill> loadSkills() throws SkillerException;
	
	/**
	 * <p>
	 * Save the repository directories.<br/>
	 * This file is a raw text file with all distinct directories.
	 * </p>
	 * <p>
	 * The resulting file will be used by the dependencies eviction form 
	 * <i>(table-dependencies.component in the Angular project)</i>.
	 * </p>
	 * @param project the current project
	 * @param changes the history of changes retrieved from the repository
	 * @throws SkillerException thrown if an exception occurs during the saving process.
	 */
	void saveRepositoryDirectories(Project project, SourceControlChanges changes) throws SkillerException;
	
	/**
	 * Load the list of all directory-paths for the repository of the given project.
	 * @param project the given project
	 * @return the resulting paths list
	 * @throws SkillerException thrown if an exception occurs during the loading process.
	 */
	List<String> loadRepositoryDirectories (Project project) throws SkillerException;
	
}
