# 
# Ubuntu Fitzhi container
# 
FROM eclipse-temurin:11.0.15_10-jre
LABEL Frederic VIDAL (frederic.vidal@fitzhi.com)

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update; \
    apt-get -y install git nginx

# Organization declared in sonarcloud.io 
ARG organization

# URL where the Fitzhi main server is installed
# The slave will connect with this server.
ARG urlApplication

# Login credential to connect with the main application.
ARG login

# Password required to be identified by the main Fitzhi application.
ARG pass

COPY fitzhi fitzhi

RUN	cd /; \
	cp fitzhi/deploy/docker-slave/default /etc/nginx/sites-enabled/default; \
	cp fitzhi/deploy/docker-slave/start-slave.sh fitzhi/deploy/back-fitzhi/start-slave.sh; \
	cp fitzhi/deploy/docker-slave/sonar-servers.json fitzhi/deploy/data/referential/sonar-servers.json; \
	echo "export DOCKER_FITZHI_BUILDTIME=#buildingTime" >> ~/.bashrc

WORKDIR /fitzhi/deploy/back-fitzhi

CMD ./start-slave.sh 

EXPOSE 8081
