# 
# Ubuntu Fitzhi slave container
# 
FROM eclipse-temurin:11.0.15_10-jre
LABEL Frederic VIDAL (frederic.vidal@fitzhi.com)

ENV DEBIAN_FRONTEND noninteractive

# Organization declared in sonarcloud.io 
ARG organization

# URL where the Fitzhi main server is installed
# The slave will connect with this server.
ARG urlApplication

# Login credential to connect with the main application.
ARG login

# Password required to be identified by the main Fitzhi application.
ARG pass

COPY fitzhi fitzhi

RUN	cd /; \
	cp fitzhi/deploy/docker-slave/start-slave.sh fitzhi/deploy/back-fitzhi/start-slave.sh; \
	echo "export DOCKER_FITZHI_BUILDTIME=#buildingTime" >> ~/.bashrc

WORKDIR /fitzhi/deploy/back-fitzhi

# Launch the slave, and terminate the container when the Spring container has ended.
ENTRYPOINT [ "./start-slave.sh" ]

EXPOSE 8081
