
== Complete a release and start a new branch 

=== Upgrade the version

Upgrade the version inside the file VERSION_FITZHI. +
Update the release 1.n-SNAPSHOT to 1.n.

=== Working on GitHub

- Merging the actual branch release-1.m to master
- Create the new branch release-1.n (where n = m+1)

=== Working on Master

.cloning the master branch
[source, shell]
----
git clone --branch master https://github.com/fitzhi/application.git
----

- Update the building script to this new branch. 

**Files concerned** +
Back-end build and test.java.yml +
codeQL-analysis-java.yml +
Front-end build and test.js.yml + 
codeQL-analysis-typescript.yml +
docker/docker/start-fitzhi.sh +
back-fitzhi/run.sh +
projects.json +
front-fitzhi/package.json


=== Merging Master into the branch release-1.n

[source, shell]
----
git clone https://github.com/fitzhi/application.git
git checkout release-1.n
git merge master
----

- Update the version of the release in the POM.xml to 1.n-SNAPSHOT

== Taking in account the new SSL certificat

IMPORTANT: **EXPIRATION DATE : 2023/02/21**

=== Locating the SSL settings for nginx :

[source, shell]
----
[vercinginx@localhost:/etc/nginx/snippets$ cat fitzhi.com.conf 
ssl_certificate /etc/ssl/certs/fitzhi.com_ssl_certificate.cer;
ssl_certificate_key /etc/ssl/private/fitzhi.com.key;
----

=== Using the SSL certificats generated by IONOS :

- copy the PRIVATE key downloaded AT THE GENERATION into **"ssl_certificate_key /etc/ssl/private/fitzhi.com.key"**
- copy the PUBLIC key download from the SSL settings URL into **"/etc/ssl/certs/fitzhi.com_ssl_certificate.cer"**

=== Taking in account the new certificate by reloading nginx

[source, shell]
----
reload nginx -s reload
----


== Deployment of Fitzhi

=== Build and deploy the Angular application to spoq.io

[source, shell]
----
cd application/front-fitzhi/scripts
sudo ./deploy.sh
----

=== Deployment of the Angular server on the spoq.fitzhi.com server

Login to spoq.fitzhi.com server.

[source, shell]
----
cd application/front-fitzhi/scripts
sudo ./deploy-local-from-spoc.sh
----

=== Build the deployments archtypes for Docker

Login to spoq.fitzhi.com server.

[source, shell]
----
sudo ./stop-backend.sh
cd release
sudo ./build.sh
cd ..
sudo ./start-backend.sh
----

=== Build and push the Docker container for the active release

[source, shell]
----
cd application/docker
./build_push_pull_run.docker.sh
----

== Special configuration for the MacOS Siline

A fix has to be added to allow the execution of tests

.webpack-dev-middleware/lib/util.js line 131
[source, shell]
----
//
// 30/04/2021
// On MacOS Silicon, to avoid the error
/*
 TypeError: Cannot read property 'range' of undefined
   at handleRangeHeaders (/Users/frvidal/work/projects/application/front-fitzhi/node_modules/webpack-dev-middleware/lib/util.js:131:21)
   at processRequest (/Users/frvidal/work/projects/application/front-fitzhi/node_modules/webpack-dev-middleware/lib/middleware.js:98:19)
*/
if ((req.headers) && (req.headers.range)) {
 const ranges = parseRange(content.length, req.headers.range);
----
