# This workflow will build a Java project with Maven.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-fitzhi

    steps:
    - uses: actions/checkout@v2
    - name: "create directories for the repositories"
      run: |
            mkdir ../git_repo_for_test
            mkdir ../git_repo_for_test/first-test
            mkdir ../git_repo_for_test/application
            ls ../git_repo_for_test
    - name: Download the first_test repository
      run: |
            echo "Cloning the first-test repository" 
            cd ../git_repo_for_test/first-test
            pwd
            git clone https://github.com/frvidal/first-test
            cd ../application
            pwd
            echo "Cloning the application repository" 
            git clone https://github.com/fitzhi/application
    - name: list the content of the testing repositories
      run: |
           pwd
           cd ..
           pwd
           cd ..
           pwd
           ls 
           echo "first-test : "
           ls -Rl ./first-test
           echo "application :  "
           ls -Rl ./application
           cd ../back-fitzhi
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true
    - name: Test with maven
      run: mvn install
