# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]
    defaults:
      run:
        working-directory: ./back-fitzhi
    steps:
    - uses: actions/checkout@v2
    - name: "create directories for the repositories"
      run: |
            mkdir ../git_repo_for_test
            ls ../git_repo_for_test
    - name: Download the first_test repository
      run: |
            echo "Cloning the first-test repository" 
            cd ../git_repo_for_test/
            git clone https://github.com/frvidal/first-test
            ls first-test
            echo "Cloning the application repository" 
            git clone https://github.com/fitzhi/application
            ls application
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Test with maven
      run: mvn install
