name: Docker Image CI

on:
  push:
    branches: [ release-1.8 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker build . --file docker/Dockerfile --tag fitzhi/application:${VERSION_FITZHI}
        docker push fitzhi/application:${VERSION_FITZHI}
