name: Docker Image CI

on:
  push:
    branches: [ release-1.8 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker build . --file docker/Dockerfile --tag fitzhi/application:${VERSION_FITZHI}
        docker push fitzhi/application:${VERSION_FITZHI}
