name: Docker Image CI

on:
  push:
    branches: [ release-1.8 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Angular Frontend
      run: |
        npm ci
        sh ./gen-build-ts.sh
        npm run test
        npm run build-prod-docker
        mv dist-docker ../spoq
      working-directory: ./front-fitzhi

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build the Backend
      run: |
        export VERSION_FITZHI=`cat ./VERSION_FITZHI`
        mvn --batch-mode clean package -DskipTests
      working-directory: ./back-fitzhi

    - name: Build the image of Fitzhi
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker build . --file ./docker/Dockerfile-linux-arm64 --tag fitzhi/application:${VERSION_FITZHI}-arm64
        docker build . --file ./docker/Dockerfile-linux-amd64 --tag fitzhi/application:${VERSION_FITZHI}-amd64
  
    - name: Deploy the image
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker push fitzhi/application:${VERSION_FITZHI}-arm64
        docker push fitzhi/application:${VERSION_FITZHI}-amd64
