# 
# Building & deploying the Fitzhi docker image into dockerhub.
# This is a nightly build.
# 
# Author : Frederic VIDAL (May 2022)
#
name: Docker Fitzhi Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '15 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
  
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      id: qemu

    - name: Build the Angular Frontend
      run: |
        npm ci
        sh ./gen-build-ts.sh
        npm run test
        npm run build-prod-docker
        mv dist-docker ../spoq
      working-directory: ./front-fitzhi

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build the Backend
      run: |
        export VERSION_FITZHI=`cat ./VERSION_FITZHI`
        mvn --batch-mode install -DskipTests
      working-directory: ./back-fitzhi

    - name: Package the Server runtime
      run: |
        export VERSION_FITZHI=`cat ./VERSION_FITZHI`
        mkdir -p fitzhi/deploy/back-fitzhi
        mv ./back-fitzhi/data fitzhi/deploy/data
        mv ./back-fitzhi/target/fitzhi-${VERSION_FITZHI}.jar	fitzhi/deploy/back-fitzhi/fitzhi-${VERSION_FITZHI}.jar
        mv ./back-fitzhi/target/application.properties	fitzhi/deploy/back-fitzhi/application.properties
        mv ./back-fitzhi/target/logback-spring.xml	fitzhi/deploy/back-fitzhi/logback-spring.xml
        mv ./docker/docker fitzhi/deploy/

    - name: Build the image of Fitzhi
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker build . --push --file ./docker/Dockerfile --platform=linux/amd64,linux/arm64 --tag fitzhi/application:${VERSION_FITZHI} --no-cache
        # docker build . --push --file ./docker/Dockerfile --platform=linux/amd64,linux/arm64 --tag fitzhi/application:${VERSION_FITZHI} --no-cache
        docker images
  