name: Docker Image CI

on:
  push:
    branches: [ release-1.8 ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Build the Angular Frontend
      run: |
        npm ci
        sh ./gen-build-ts.sh
        npm run test
        npm run build-prod-docker
        mv dist-docker ../spoq
      working-directory: ./front-fitzhi

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build the Backend
      run: |
        export VERSION_FITZHI=`cat ./VERSION_FITZHI`
        mvn --batch-mode install -DskipTests
      working-directory: ./back-fitzhi

    - name: Package the Server runtime
      run: |
        mkdir -p deploy/back-fitzhi
        mv ./back-fitzhi/data ./deploy/data
        mv ./back-fitzhi/target/fitzhi-1.8-SNAPSHOT.jar	deploy/back-fitzhi/fitzhi-1.8-SNAPSHOT.jar
        mv ./back-fitzhi/target/application.properties	deploy/back-fitzhi/application.properties
        mv ./back-fitzhi/target/logback-spring.xml	deploy/back-fitzhi/logback-spring.xml
    	  cp ./docker/docker/default /etc/nginx/sites-enabled/default
  	    cp ./docker/docker/start-fitzhi.sh ./deploy/back-fitzhi/start-fitzhi.sh
	      cp ./docker/docker/sonar-servers.json ./deploy/data/referential/sonar-servers.json

    - name: Build the image of Fitzhi
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker build . --file ./docker/Dockerfile --platform=linux/amd64,linux/arm64 --tag fitzhi/application:${VERSION_FITZHI}
  
    - name: Deploy the image
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        docker push fitzhi/application:${VERSION_FITZHI}
