# 
# Pull and run the Fitzhi docker image of a slave of Fitzhi.
# 
# Author : Frederic VIDAL (July 2022)
#
name: Fitzhi slave runner

on:
  push:
    branches: [ release-1.9 ]
  schedule:
    - cron: '20 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Pull and run the slave of Fitzhi
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        export FITZHI_URL="http://spoq.fitzhi.com:8082"
        echo "Calling the slave for the project..."
        echo "------------------------------------"
        echo ""
        export GITHUB_URL=`git remote get-url origin`
        echo ${GITHUB_URL} 
        echo ${FITZHI_URL} 
        docker pull fitzhi/slave:${VERSION_FITZHI}
        docker run --network host --name slave  \
          -e "organization=fitzhi" \
          -e "applicationUrl=${FITZHI_URL}" \
          -e "login=${FITZHI_LOGIN}" \
          -e "pass=${FITZHI_PASSWORD}" \
          -d fitzhi/slave:${VERSION_FITZHI}
        sleep 1m
        curl -v http://localhost:8081/api/test/ping
        sleep 1m
        curl -v -X PUT -H "Content-Type:  application/json"  -d '{"urlRepository": ${GITHUB_URL}' http://localhost:8081/api/project/analysis
      env:
        FITZHI_LOGIN: ${{ secrets.FITZHI_LOGIN }}
        FITZHI_PASSWORD: ${{ secrets.FITZHI_PASSWORD }}

  