# 
# Pull and run the Fitzhi docker image of a slave of Fitzhi.
# 
# Author : Frederic VIDAL (July 2022)
#
name: Fitzhi slave runner

on:
  push:
    branches: [ release-1.9 ]
  schedule:
    - cron: '20 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1200
    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Pull and run the slave of Fitzhi
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        export FITZHI_URL="http://spoq.fitzhi.com:8082"
        echo "Calling the slave for the project..."
        echo "------------------------------------"
        echo ""
        export GITHUB_URL=`git remote get-url origin`
        echo $GITHUB_URL
        export GITHUB_BRANCH=`git rev-parse --abbrev-ref HEAD`
        echo $GITHUB_BRANCH
        docker pull fitzhi/slave:${VERSION_FITZHI}
        docker run --network host --name slave  \
          -e "organization=fitzhi" \
          -e "applicationUrl=${FITZHI_URL}" \
          -e "login=${FITZHI_LOGIN}" \
          -e "pass=${FITZHI_PASSWORD}" \
          -d fitzhi/slave:${VERSION_FITZHI}
        sleep 30s
        # curl -v -X PUT -H "Content-Type:  application/json" \
        #      -d "{\"urlRepository\":\"${GITHUB_URL}\", \"branch\":\"${GITHUB_BRANCH}\"}" \
        #     http://localhost:8081/api/project/analysis
        docker stop slave
        docker rm slave
      env:
        FITZHI_LOGIN: ${{ secrets.FITZHI_LOGIN }}
        FITZHI_PASSWORD: ${{ secrets.FITZHI_PASSWORD }}

    - name: Testing the slave with the Spring framework
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        export FITZHI_URL="http://spoq.fitzhi.com:8082"
        mkdir ../spring-test
        cd ../spring-test
        git clone --branch main https://github.com/spring-projects/spring-framework.git
        cd ./spring-framework
        export GITHUB_URL=`git remote get-url origin`
        echo $GITHUB_URL
        export GITHUB_BRANCH=`git rev-parse --abbrev-ref HEAD`
        echo $GITHUB_BRANCH
        docker run --network host --name slave \
          -e "organization=fitzhi" \
          -e "applicationUrl=${FITZHI_URL}" \
          -e "login=${FITZHI_LOGIN}" \
          -e "pass=${FITZHI_PASSWORD}" \
          -d fitzhi/slave:${VERSION_FITZHI}
        sleep 30s
        # curl -v -X PUT -H "Content-Type:  application/json" \
        #      -d "{\"urlRepository\":\"${GITHUB_URL}\", \"branch\":\"${GITHUB_BRANCH}\"}" \
        #      http://localhost:8081/api/project/analysis
        docker stop slave
        docker rm slave
        cd ..
        rm -rf spring-framework
      env:
        FITZHI_LOGIN: ${{ secrets.FITZHI_LOGIN }}
        FITZHI_PASSWORD: ${{ secrets.FITZHI_PASSWORD }}

    - name: Testing the slave with Spring boot
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        export FITZHI_URL="http://spoq.fitzhi.com:8082"
        git clone --branch main https://github.com/spring-projects/spring-boot.git
        cd ./spring-boot
        export GITHUB_URL=`git remote get-url origin`
        echo $GITHUB_URL
        export GITHUB_BRANCH=`git rev-parse --abbrev-ref HEAD`
        echo $GITHUB_BRANCH
        docker run --network host --name slave \
          -e "organization=fitzhi" \
          -e "applicationUrl=${FITZHI_URL}" \
          -e "login=${FITZHI_LOGIN}" \
          -e "pass=${FITZHI_PASSWORD}" \
          -d fitzhi/slave:${VERSION_FITZHI}
        sleep 30s
        # curl -v -X PUT -H "Content-Type:  application/json" \
        #      -d "{\"urlRepository\":\"${GITHUB_URL}\", \"branch\":\"${GITHUB_BRANCH}\"}" \
        #      http://localhost:8081/api/project/analysis
        docker stop slave
        docker rm slave
        cd ..
        rm -rf spring-boot
      env:
        FITZHI_LOGIN: ${{ secrets.FITZHI_LOGIN }}
        FITZHI_PASSWORD: ${{ secrets.FITZHI_PASSWORD }}
  
    - name: Testing the slave with Spring security
      run: |
        export VERSION_FITZHI=`cat ./back-fitzhi/VERSION_FITZHI`
        export FITZHI_URL="http://spoq.fitzhi.com:8082"
        git clone --branch main https://github.com/spring-projects/spring-security.git
        cd ./spring-security
        export GITHUB_URL=`git remote get-url origin`
        echo $GITHUB_URL
        export GITHUB_BRANCH=`git rev-parse --abbrev-ref HEAD`
        echo $GITHUB_BRANCH
        docker run --network host --name slave \
          -e "organization=fitzhi" \
          -e "applicationUrl=${FITZHI_URL}" \
          -e "login=${FITZHI_LOGIN}" \
          -e "pass=${FITZHI_PASSWORD}" \
          -d fitzhi/slave:${VERSION_FITZHI}
        sleep 30s
        # curl -v -X PUT -H "Content-Type:  application/json" \
        #     -d "{\"urlRepository\":\"${GITHUB_URL}\", \"branch\":\"${GITHUB_BRANCH}\"}" \
        #     http://localhost:8081/api/project/analysis
        docker stop slave
        docker rm slave
        cd ..
        rm -rf spring-security
      env:
        FITZHI_LOGIN: ${{ secrets.FITZHI_LOGIN }}
        FITZHI_PASSWORD: ${{ secrets.FITZHI_PASSWORD }}
