# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, release-1.9 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-fitzhi    
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: Building and testing
      run: |
        npm --version
        npm ci
        npm run build
        npm run test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: front-fitzhi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: (matrix.node-version == '16.x')
    #
    # These lines are commented because I (Frederic VIDAL) could not find a way to commit changes to another repository from this repository
    #
    # - name: Fitzhi front application deployment
    #  if: ${{ (github.ref == 'refs/heads/release-1.4') && (matrix.node-version == '12.x') && ! failure() }}
    #  run: |
    #    echo "I only run for the branch "${{github.ref}} and node version ${{matrix.node-version}}
    #    ./deploy.sh

